dist: xenial
language: go
before_install:
  - chmod +x buildscripts/install_hugo.sh buildscripts/upload_s3.sh
  - rm -r public
  - bash buildscripts/install_hugo.sh
  - pip3 install awscli
jobs:
  include:
    - stage: "Build and Deploy" 
      name: "Build and deploy the Hugo static website"
      script:
        - hugo
        - buildscripts/upload_s3.sh $AWS_ACCESS_KEY $AWS_SECRET_KEY
        