dist: xenial
language: python
python:
  - "3.7"
before_install:
  - chmod +x buildscripts/cleanup.py buildscripts/upload_s3.sh
  - python3.7 buildscripts/cleanup.py
  - pip3 install hugo
  - pip3 install awscli
jobs:
  include:
    - stage: "Build and Deploy" 
      name: "Build and deploy the Hugo static website"
      script:
        - hugo
        - buildscripts/upload_s3.sh $AWS_ACCESS_KEY $AWS_SECRET_KEY
        